### ISSUE TITLE
Is there some errors atthe line 70 in dqn.py

### ISSUE THREAD

**Issue by szcdlsq** [HyunwooOh/Reinforcement-Learning#1]
When I test your codes,it seems that env.step(1) is not right ,because the plate in the game remains still and the score is really low

**Comment by HyunwooOh** [comment]
Thank you for your question. 
That is called 'no-op actions' which generate different initial states of environment. 
This post will be helpful:
https://stats.stackexchange.com/questions/351035/why-does-deep-q-learning-have-do-nothing-actions
